import { Preset } from '../config/types.js';

export const PRESETS: Record<string, Preset> = {
    unreal: {
        name: 'unreal',
        description: 'Unreal Engine 5 game development project',
        ignorePatterns: [
            'Binaries/**',
            'Intermediate/**',
            'Saved/**',
            'DerivedDataCache/**',
            'Build/**',
            '.vs/**',
            '.idea/**',
            '*.sln',
            '*.vcxproj',
            '*.vcxproj.*',
            'Plugins/*/Binaries/**',
            'Plugins/*/Intermediate/**',
            'Content/**/*.uasset',
            'Content/**/*.umap',
            '*.exe',
            '*.dll',
            '*.so',
            '*.dylib',
            '*.pdb',
            '*.target',
            '*.modules',
        ],
        extensions: ['.cpp', '.h', '.c', '.inl', '.cs', '.usf', '.ush', '.uplugin', '.uproject', '.ini'],
    },
    unity: {
        name: 'unity',
        description: 'Unity game development project',
        ignorePatterns: [
            'Library/**',
            'Temp/**',
            'Build/**',
            'Builds/**',
            'Logs/**',
            'obj/**',
            '*.csproj',
            '*.unityproj',
            '*.sln',
            '.vs/**',
            'Assets/Plugins/Editor/**',
            'Assets/StreamingAssets/**',
            'ProjectSettings/**',
            'UserSettings/**',
            '*.apk',
            '*.aab',
            '*.exe',
            '*.app',
        ],
        extensions: ['.cs', '.shader', '.cginc', '.hlsl', '.glsl', '.compute', '.asmdef'],
        // Large or binary Unity assets — indexed as a single chunk containing only the file path,
        // so semantic search can locate them by name without embedding their contents.
        filenameOnlyExtensions: [
            // Unity-serialized assets
            '.unity', '.prefab', '.asset', '.mat', '.anim', '.controller', '.overrideController',
            '.mask', '.physicMaterial', '.physicsMaterial2D', '.mixer', '.playable', '.signal',
            '.spriteatlas', '.spriteatlasv2', '.terrainlayer', '.lighting', '.giparams',
            '.shadergraph', '.shadersubgraph', '.preset', '.brush', '.flare', '.fontsettings',
            '.guiskin', '.cubemap', '.renderTexture',
            // 3D models
            '.fbx', '.obj', '.blend', '.dae', '.3ds', '.ma', '.mb', '.max',
            // Textures / images
            '.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tga', '.psd', '.tif', '.tiff', '.exr', '.hdr',
            // Audio
            '.wav', '.mp3', '.ogg', '.aiff', '.aif', '.flac',
            // Video
            '.mp4', '.mov', '.webm', '.avi',
            // Fonts
            '.ttf', '.otf',
        ],
    },
    node: {
        name: 'node',
        description: 'Node.js / JavaScript / TypeScript project',
        ignorePatterns: [
            'node_modules/**',
            'dist/**',
            'build/**',
            'out/**',
            '.next/**',
            '.nuxt/**',
            'coverage/**',
            '.nyc_output/**',
            '*.min.js',
            '*.min.css',
            '*.bundle.js',
            '*.chunk.js',
            '*.log',
            '.env',
            '.env.*',
            '*.local',
        ],
        extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.json', '.md'],
    },
    python: {
        name: 'python',
        description: 'Python project',
        ignorePatterns: [
            '__pycache__/**',
            '*.pyc',
            '*.pyo',
            '*.pyd',
            '.Python',
            'venv/**',
            'env/**',
            '.venv/**',
            '.env/**',
            'eggs/**',
            '*.egg-info/**',
            '.pytest_cache/**',
            '.mypy_cache/**',
            '.ruff_cache/**',
            'htmlcov/**',
            '.tox/**',
            'site-packages/**',
            '*.egg',
            '*.manifest',
            '*.spec',
        ],
        extensions: ['.py', '.pyi', '.pyx', '.pxd', '.ipynb'],
    },
    rust: {
        name: 'rust',
        description: 'Rust project',
        ignorePatterns: [
            'target/**',
            'Cargo.lock',
            '**/*.rs.bk',
            '*.pdb',
        ],
        extensions: ['.rs', '.toml'],
    },
    go: {
        name: 'go',
        description: 'Go project',
        ignorePatterns: [
            'vendor/**',
            '*.exe',
            '*.exe~',
            '*.dll',
            '*.so',
            '*.dylib',
            '*.test',
            '*.out',
        ],
        extensions: ['.go', '.mod', '.sum'],
    },
    java: {
        name: 'java',
        description: 'Java / JVM project',
        ignorePatterns: [
            'target/**',
            'build/**',
            'out/**',
            '.gradle/**',
            '*.class',
            '*.jar',
            '*.war',
            '*.ear',
            '*.nar',
            '.mvn/**',
            'mvnw',
            'mvnw.cmd',
            'gradlew',
            'gradlew.bat',
        ],
        extensions: ['.java', '.kt', '.kts', '.scala', '.groovy', '.gradle', '.xml'],
    },
    web: {
        name: 'web',
        description: 'Frontend web project (React, Vue, etc.)',
        ignorePatterns: [
            'node_modules/**',
            'dist/**',
            'build/**',
            '.next/**',
            '.nuxt/**',
            'coverage/**',
            '*.min.js',
            '*.min.css',
            '*.bundle.js',
            '*.chunk.js',
            '*.map',
            '.env',
            '.env.*',
        ],
        extensions: ['.ts', '.tsx', '.js', '.jsx', '.vue', '.svelte', '.css', '.scss', '.sass', '.less', '.html', '.json', '.md'],
    },
    minimal: {
        name: 'minimal',
        description: 'Minimal preset - only essential ignores',
        ignorePatterns: [
            'node_modules/**',
            '.git/**',
            '.svn/**',
            '.hg/**',
        ],
        extensions: [],
    },
};

export function getPreset(name: string): Preset | undefined {
    return PRESETS[name];
}

export function getPresetNames(): string[] {
    return Object.keys(PRESETS);
}

export function getPresetDescriptions(): Array<{ name: string; description: string }> {
    return Object.values(PRESETS).map(p => ({
        name: p.name,
        description: p.description,
    }));
}
